"""Linear equation formatiing"""

MDASH = u'\u2014'


def equation(value):
    """Format equation generated by linear.calc_equation"""
    line_x = fraction(value.get('x'), False)
    line_b = fraction(value.get('b'), True)

    line1 = '    ' + line_x[0] + '  ' + line_b[0]
    line2 = 'y = ' + line_x[1] + 'x ' + line_b[1]
    line3 = '    ' + line_x[2] + '  ' + line_b[2]

    return line1 + '\n' + line2 + '\n' + line3


def fraction(value, sign):
    line = ['', '', '']

    space = '  '
    if value < 0:
        line = [space, '- ', space]
    elif sign:
        line = [space, '+ ', space]

    if value.numerator % value.denominator == 0:
        line[0] += ' '
        line[1] += str(abs(value.numerator / value.denominator))
        line[2] += ' '
    else:
        numerator_size = len(str(abs(value.numerator)))
        denominator_size = len(str(abs(value.denominator)))
        size = numerator_size if numerator_size > denominator_size else denominator_size

        line[0] += str(abs(value.numerator)).ljust(size)
        line[1] += MDASH * size
        line[2] += str(abs(value.denominator)).ljust(size)

    return line
